# CachyOS-Tune-Performance Funding Configuration
# This enables the GitHub Sponsor button automatically

github: [YunShanz-MC]  # Ganti dengan GitHub username-mu
patreon: YunShanzMC    # Kalau punya Patreon, ganti username
ko_fi: yunshanzmc      # Ko-fi username (lowercase)
buy_me_a_coffee: YunShanzMC  # Buy Me a Coffee username
paypal: [shanz@example.com]  # Email PayPal-mu (dalam kurung siku)
open_collective: cachyos-tune-performance  # Opsional

# Custom message sponsor page
title: Support CachyOS Performance Optimization
message: |
  Thanks for supporting CachyOS-Tune-Performance! Your contribution helps optimize Linux for gaming. Funds go toward testing, new features, and community support.

  Special thanks to all contributors and users who make this project possible! 🚀

# Sponsor tiers
tiers:
  - name: Coffee Supporter
    description: Buy me a coffee to keep the project caffeinated!
    amount: 3
  - name: Benchmark Sponsor
    description: Fund hardware testing and performance analysis
    amount: 10
  - name: Feature Request
    description: Priority support for custom optimization requests
    amount: 25
